[author] 
name = "kdqed"
website = "https://kdqed.com"

[colors]
b = ["#1d2228", "#2f3741", "#4d5a6a", "#67788e"]

v = ["#a177a1", "#d9a6d9"]
i = ["#5cb9cc", "#7dd6e8"]
b = ["#6991bf", "#8fbcef"]
g = ["#699669", "#8cd98c"]
y = ["#bfbf75", "#e8e87d"]
o = ["#cd9d7e", "#efcdb8"]
r = ["#a66663", "#ebb0ad"]

w = ["#99c8e6", "#b8ddf5", "#cce8ff", "#ebf6ff"]

